### ISSUE TITLE
Feature request: GPG-sign the tag that TagBot creates

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaRegistries/TagBot#11]
Currently, I manually create tags on the command line, which allows me to sign the tags I create with my personal GPG key.

It would be great if TagBot had the ability to GPG-sign the tags that it creates (using its own GPG key, presumably).

**Comment by DilumAluthge** [comment]
(From a [Slack discussion](https://julialang.slack.com/archives/C6M4DQA5P/p1557567686038400?thread_ts=1557547452.037000&cid=C6M4DQA5P) with @fredrikekre)

**Comment by christopher-dG** [comment]
This is a great idea. However, a brief look at the [API docs](https://developer.github.com/v3/git/tags/#create-a-tag-object) doesn't make it clear how to actually do this. I'll do some digging.

**Comment by christopher-dG** [comment]
I sent in a support ticket but I'm pretty sure this is not possible.

There's a possible workaround to support signed tags:

Currently when creating a tag fails because it already exists, everything stops and an error is reported. But, we could instead check to see if a GitHub release exists and if not, continue to create the release. This would allow you to manually create a signed tag before TagBot runs, and still have your GitHub release created automatically. It's not really ideal though, because you lose guaranteed permanence of your Git tags and it doesn't really automate much anymore. I don't think it's a terrible tradeoff though, seeing as very few people actually use GPG in practice.

**Comment by christopher-dG** [comment]
A more involved workaround: Use CLI Git or LibGit2 to create and push the tag. This one seems fun so I'll look into when I have time :slightly_smiling_face:.
