### ISSUE TITLE
TagBot/JuliaRegistrator tagging different git SHA

### ISSUE THREAD

**Issue by dehann** [JuliaRegistries/TagBot#159]
Hi,  I triggered a release with JuliaRegistrator on repo `branch=release/v0.7`:
JuliaRobotics/RoME.jl#296

The returning comment correctly states which SHA to use `1b92727` (https://github.com/JuliaRobotics/RoME.jl/issues/296#issuecomment-643723949):
```
git tag -a v0.7.1 -m "<description of version>" 1b92727...
```

After being merged in the Registry, Tagbot Action runs on the local RoME repo but then drops the tag on a completely different SHA `06522b4`?
![Screenshot from 2020-06-14 02-45-47](https://user-images.githubusercontent.com/6412556/84586939-45e76800-ade9-11ea-9bd3-d9f2ad10cd14.png)

Similarly if I clone the repo down to my local computer:
![Screenshot from 2020-06-14 02-46-44](https://user-images.githubusercontent.com/6412556/84586955-5ac3fb80-ade9-11ea-9876-d1f8c32024cd.png)

The tag should be on the `release/v0.7` branch, commit `1b92727` (as in the comment above) -- but looks like TagBot had incorrectly assumed `master` instead and used `06522b4` for the tag?  I'm pretty sure this was working before, but not seeing a recent PR here on TagBot that might indicate when a change has occurred.  Am I perhaps missing something, or is this a legitimate bug?

**Comment by christopher-dG** [comment]
I can see why this is considered weird/wrong behaviour, but I don't consider it to be a bug. TagBot doesn't care about how you triggered Registrator, it only cares about the tree SHA that ends up in the registry. Because the tree SHA depends on the files checked into the repo and nothing else, there can be multiple commits with the same tree SHA. For example, if you make 10 empty commits, they will all have the same tree SHA. Or, more realistically, if you merge a pull request from `master` to `release/v0.7` with a merge commit, those branches will have different commits at their tips but the same content and therefore the same tree SHA.

So now TagBot has to choose between these two commits (or rather, which one to encounter first). It checks the default branch (`master` in this case) before any other branches for a commit that matches the desired tree SHA because the commit we're looking for is almost always somewhere on that branch, and is often on no other branch. So that's why your tag is on the latest `master` commit and not the latest `release/v0.7` commit. Technically it makes no difference, because the content addressed by the tag is the exact same either way.

If we really wanted the tag to be on the release branch specifically, then TagBot could be changed to look at the registry PR and check the commit listed there before anything else. You do lose a minor benefit if you tag a different commit than what's on master though: you'll no longer get the "<n> commits to <branch> since this release" message on the release page. 

Sorry this was so long-winded, hopefully it makes sense.

**Comment by dehann** [comment]
Hi @christopher-dG , thanks for the reply, however, going to have to disagree.  Might be preference here, but for my use case I definitely need more rigor.  To repeat, the commit SHA on `RoME:master` is `06552b4` while the SHA on `RoME:release/v0.7` is `1b92727`.

> branches will have different commits at their tips but the same content

Different SHAs in git is a **significant** differentiator -- no guessing allowed here.  For example, what would happen if development continues on `master` before TagBot is run? 

> it only cares about the tree SHA that ends up in the registry

That can be even more worrying since the SHAs in Registry don't match up with the repo's they pointing to.  I assume the `git-tree-sha1` you talking about is `aa55a73`...  [From General registry `R/RoME/Versions.toml`](https://github.com/JuliaRegistries/General/tree/master/R/RoME):
```
["0.7.1"]
git-tree-sha1 = "aa55a7312b0048f1c2f7a83a73a2ec7d984380ce"
```

Although I do not see this `aa55a73` SHA in the RoME commit history, so I can't determine how that happened...  For comparison the git-submodule system is very explicit and precise about the remote repo SHA.

> branches will have different commits at their tips but the same content and therefore the same tree SHA

Is the `git-tree-sha` recalculated by `JuliaRegistrator` or `TagBot` based on the content in whichever branch the user specifies, like `branch=release/v0.7` in my case?  In other words, if `master` where to have different content than `release/v0.7` then TagBot will change its behavior to chose a different commit somewhere in the history?  Or will TagBot only consider the tips of all current branches in its search?  How do we know where TagBot is going to land??  

> So now TagBot has to choose between these two commits

TagBot should not be choosing, it should do the described task from the original action request -- i.e. `register branch=release/v0.7`, which at that point of time is at `1b92727`.  This is already proposed by the bots themselves 
```
git tag -a v0.7.1 -m "<description of version>" 1b927271cdeb44dc034b99e399792efd9c1e346f
git push origin v0.7.1
``` 

This SHA uncertainty is not okay when building larger production type systems.  At absolute minimum, the bots response should then stipulate that it is **NOT** running the above command, but doing something different.

> So that's why your tag is on the latest master commit and not the latest release/v0.7 commit.

If that is the long term behavior for TagBot then in my case it is best to uninstall TagBot and do it manually for more production-style rigor.

> If we really wanted the tag to be on the release branch specifically, 

Yes definitely, that is how Julia does it's releases too, no?

> then TagBot could be changed to look at the registry PR and check the commit listed there before anything else.

I had assumed that was already the behavior.
```
git tag -a v0.7.1 -m "<description of version>" 1b927271cdeb44dc034b99e399792efd9c1e346f
git push origin v0.7.1
```

> you'll no longer get the " commits to since this release" message on the release page

Is that really true:  can it not use the current system find the PRs and Issues for release page description, but the actual action for tagging can just be the already available SHA and splicing together the itemized description?

**Comment by christopher-dG** [comment]
> For example, what would happen if development continues on master before TagBot is run?

Nothing changes, the tag still points to the exact same content.

> I cannot find this aa55a73 SHA in the RoME commit history

Because it's a *tree* SHA, not a *commit* SHA. And as I explained, this tree SHA happens to be shared by a few different commits. The Julia registry and package manager work with tree SHAs, and not commit SHAs. That's where this whole disagreement/misunderstanding is coming from. If you want to verify that the tree SHA does exist somewhere in your repo, run `git log --all --format="%H %T" | grep aa55a7312b0048f1c2f7a83a73a2ec7d984380ce` and you'll get the two commits in question here.

> Is the git-tree-sha recalculated by JuliaRegistrator or TagBot based on the content in whichever branch the user specifies[...]

Registrator figures out which *commit* you triggered it at so that it can tell the registry exactly what content it should expect, it doesn't care which branch that's on. Branch is generally irrelevant when registering stuff. TagBot guarantees that the commit it tags has **the exact same content** that the registry will give you. It's important to note that the registry also has no idea what branch or commit it's going to get, it only knows the hash of the content as a whole (the tree SHA). 

> This SHA uncertainty is not okay when building larger production type systems. 

This is my main confusion with this issue, it seems that you might think that your tags will point to different code than what's contained in the registry. I can assure that this is never the case.

> At absolute minimum, the bots response should then stipulate that it is NOT running the above command, but doing something different. [...] I had assumed that was already the behavior.

Registrator and TagBot are not the same bot. Obviously they're related, but that message is not saying "here's what TagBot is going to do".

> Yes definitely, that is how Julia does it's releases too, no?

Yes, but Julia also doesn't merge those release branches into master from what I can tell.

> Is that really true: can it not use the current system find the PRs and Issues for release page description, but the actual action for tagging can just be the already available SHA and splicing together the itemized description?

Sorry, I meant to write `<n> commits to <branch> since this release` but Markdown comments swallowed up some info. What I mean is this:

![Capture](https://user-images.githubusercontent.com/17228795/84599955-6b04c680-ae3b-11ea-9b15-9d137bb5c364.PNG)

The changelog doesn't change at all, it's just the GitHub feature of tracking changes since release.

---

To summarize:

When a new version goes into the registry, there is no record of what commit or what branch that version was at. All that's recorded is a hash of the content. That's why the difference between tagging the commit on master and the commit on the release branch is not meaningful --- there is technically no right answer as to which one deserves the tag more than the other. I chose to resolve that ambiguity by preferring a commit on the default branch over one on a branch that might get deleted tomorrow (TagBot knows nothing about your branch naming and preservation conventions other than which branch is default).

Now that of course ignores the human aspect of it all: you're using `release/vX.Y` as a release target, triggered Registrator specifically on that branch, and so you expect your tags to point to those commits. And that totally makes sense! So to leave this with some actionable points to make TagBot behave more like a human being would expect it to:

- You could refrain from merging your release branch into master until after the tag has been created. Your releases would then say `<n> commits to `release/vX.Y` since this release`
- You could change your default branch to the most recent release branch and maintain a `dev` branch or similar.
- I could make TagBot consider the commit listed in the registry PR before all other commits. I'll probably do this.

**Comment by dehann** [comment]
Thanks again, but sounds like we are on diverging paths here.  We'll keep trying to use Tagbot but sounds like it might be mismatch with what we need.

I am/was not aware that git uses both `sha` and `tree-sha` -- I'll have to look deeper into how those two come together before I can make useful comments there.  Thanks for the command, I tried it and and get both the `1b92` and `0652` tag numbers:
```
[git] JuliaRobotics/RoME.jl:release/v0.7
$ git log --all --format="%H %T" | grep aa55a7312b0048f1c2f7a83a73a2ec7d984380ce
1b927271cdeb44dc034b99e399792efd9c1e346f aa55a7312b0048f1c2f7a83a73a2ec7d984380ce
06522b4ec7605aba2120fab4cf128fded9b84465 aa55a7312b0048f1c2f7a83a73a2ec7d984380ce
```

Perhaps some context on how we use git for releases which might help explain why there is difficulty:  We are not using a default branch release strategy (like master) -- sounds like that might be an assumption made by Tagbot.  We also actively decide against using a `dev` branch strategy for a couple of reasons.  We decided to use a different git-flow model where release branches drift away from master at each minor version series, and thereby provide a bug fix option (via backports) for long term stability.  Release branches can also pass QC as able without hampering ongoing development work.  We also do not merge release branches back into master at any point in the future.  This simplifies adherence to the semver requirements.  We also definitely do not want to place release tags on `master`, since `master` in our approach serves as the primary interface point between various developers.

**Comment by christopher-dG** [comment]
Thanks for the extra context, that's helpful. I've opened #161 to mention the fix that I can offer.

**Comment by dehann** [comment]
I just checked a similar tag further back on RoME v0.6.4 where TagBot did place the tag on the right place (on release branch) `986268c` which is on the `release/v0.6` branch that had already diverged from `master`:
![Screenshot from 2020-06-14 15-57-43](https://user-images.githubusercontent.com/6412556/84602797-deb4cc80-ae57-11ea-99f3-90c3aae7e306.png)

So if I'm understanding how you explain `git-tree-sha`, git is using a hidden internal SHA which is a hash of the content (not dictated by date/time or other inputs) and TagBot is choosing a visible regular git SHA from the set of all equivalent code "derived from the one" hidden `git-tree-sha` points -- seems bit weird, but okay...

To be clear on the current stable version of TagBot, there is uncertainty about which regular git SHA will be used for tagging, and can easily differ from the prescribed command as we discussed above, and we should accept that as expected behavior?  Furthermore, tags will not necessarily land on the branch you request when calling on JuliaRegistrator unless they fall under a different 'hidden' git-tree-sha.  This might change if there is a resolution to #161 (thanks).

I'd recommend a concise and clear statement in the JuliaRegistrator/TagBot reply once a release request is received from the user, on what TagBot is going to do, especially if it is going to differ from the suggested tag SHA.

**Comment by christopher-dG** [comment]
> So if I'm understanding how you explain git-tree-sha, git is using a hidden internal SHA which is a hash of the content (not dictated by date/time or other inputs) and TagBot is choosing a visible regular git SHA from the set of all equivalent code "derived from the one" hidden git-tree-sha points

Exactly. The registry and package manager deal only in content hashes, and not with Git commits. I am not the right person to explain why things work this way, @StefanKarpinski would perhaps have a good answer!

> To be clear on the current stable version of TagBot, there is uncertainty about which regular git SHA will be used for tagging, and can easily differ from the prescribed command as we discussed above, and we should accept that as expected behavior? 

Well, there's no uncertainty, the algorithm just doesn't fit well with your release strategy. That algorithm will change to take the commit Registrator was triggered on into account.

> Furthermore, tags will not necessarily land on the branch you request when calling on JuliaRegistrator unless they fall under a different 'hidden' git-tree-sha.

A tag does not land on a branch, it lands on a commit. So again, this is just an implementation detail where currently the commit that happens to be on master branch is preferred over the commit that happens to be on the release branch. In case it's not already clear, the Git tags that TagBot creates have absolutely no effect on the Julia registry or the Julia package manager and even if they did, you would still get the same content.

> I'd recommend a concise and clear statement in the JuliaRegistrator/TagBot reply once a release request is received from the user, on what TagBot is going to do, especially if it is going to differ from the suggested tag SHA.

Again, they're different bots and Registrator's comment doesn't indicate anything about what TagBot will do, but TagBot will change to behave more like Registrator suggests that you, as a human, do.

**Comment by dehann** [comment]
Understood thanks.  I just tested it on a different repo and thought I'd add one last picture to help document how things are currently happening.

> How do we know where TagBot is going to land??

I requested a release from JuliaRegistrator for Caesar v0.5.2 (JuliaRobotics/Caesar.jl#567) on `branch=release/v0.5`, and also made sure master had already progressed beyond the tag point.  My mental model was/is expecting the tag to be by the 'green dot' commit.  The tag was then added via Tagbot automation at the 'red dot' commit:
![Screenshot from 2020-06-14 20-52-25](https://user-images.githubusercontent.com/6412556/84608842-4c75ee00-ae82-11ea-8973-320e5107e8b3.png)

The two commits have different git SHAs but the same (still slightly mysterious to me `git-tree-sha`), and hence we trust the content the user will get is exactly the same (even though it looks like its coming from a different branch).

> Well, there's no uncertainty, the algorithm just doesn't fit well with your release strategy

> TagBot will change to behave more like Registrator suggests that you, as a human, do

Thanks that will help a lot!  I do think it's important since Julia itself uses the same strategy.  Thanks for taking the time to respond and PR!
