### ISSUE TITLE
Automatic releases on a specified branch?

### ISSUE THREAD

**Issue by Paveloom** [JuliaRegistries/TagBot#163]
Is it possible to use TagBot for automatic creation of releases on a branch different from the default one? I have just used Registrator (Web Interface) to update the version of my package in General registry using the `master` branch (which isn't the default one), this seemed to work just fine. However, TagBot created a release on the `develop` branch (which is the default one).

**Comment by christopher-dG** [comment]
I'm not entirely sure what you mean, since tags point to commits, not branches. The only reason a branch has anything to do with GitHub releases is the "N commits since this release" indicator on the release page. When the commit being tagged is the same as the commit at the tip of the default branch, the release ref is set to the default branch which has the exact same effect as using the commit, but also adds that N commits indicator.

Maybe you could clarify what exactly you mean and/or link the repo in question?

**Comment by Paveloom** [comment]
> When the commit being tagged is the same as the commit at the tip of the default branch, the release ref is set to the default branch which has the exact same effect as using the commit, but also adds that N commits indicator.

This is exactly what happens here, but somehow I don't really get to choose what commit is being tagged by TagBot, because this just happens automatically. I do, however, get to choose a tag / branch using Registrator's Interface, but this doesn't affect TagBot's actions, I suppose.
 
> Maybe you could clarify what exactly you mean and/or link the repo in question?

What I meant by branches is precisely what you described: tagging one of the commits at the tips of these branches. My question is about whether can I choose between them. I would like to have TagBot creating a GitHub release with a tag on a tip of the `master` branch (not default one) every time my package is updated in the registry, instead of doing the same on the `develop` branch (default one) as it happens now.

The repository in question is [Scats.jl](https://github.com/paveloom-j/Scats.jl), albeit, I have already deleted the last release (which had a tag at the tip of the `develop` branch) and recreated it, tagging the last commit on the `master` branch. All of the previous releases have been created when `master` was the default branch, so they should be left out of consideration.

**Comment by christopher-dG** [comment]
When you choose a branch with Registrator, it just translates that into a commit (whatever is on the tip of that branch). So TagBot then tags that commit (#161 and the issue linked in there is sort of related).
If you want your tags to always be put on the tip of a specific branch, they'll end up being on the wrong commit now and then if you make changes before the registration PR is merged, so that's a no go. I guess maybe what you want is to be able to have GitHub display "N commits to \<arbitrary branch I choose\> since this release", instead of \<default branch\>. But honestly this is a rare enough case that I don't really think it's worth adding extra code and config for.

**Comment by Paveloom** [comment]
> If you want your tags to always be put on the tip of a specific branch, they'll end up being on the wrong commit now and then if you make changes before the registration PR is merged, so that's a no go.

No-no, I meant focusing on the contents of one specific commit which was used by Registrator. Progressing on the branch shouldn't (and is not happening now, as far as I can tell) break anything. Well, at least if deletion and overriding are prohibited, I guess.

> So TagBot then tags that commit (#161 and the issue linked in there is sort of related).

Apparently, yes, the issue #159 is exactly my problem, except maybe a minor difference that the author uses another release strategy. I've read that thread, and your explanations about `git-tree-sha` have clarified to me how TagBot behaves on this matter. The confusion with a tag not being by a commit on a release branch, but rather by a commit on the default branch (even though their contents are exactly the same), is exactly what I would like to avoid by some sort of configuration. @dehann also have [an illustration](https://github.com/JuliaRegistries/TagBot/issues/159#issuecomment-643852293) of this. You have stated this algorithm in #161, so my suggestion to this (according to what I meant in this issue) would look something like this:

```python
for commit in specified_branch.commits:
  if commit.tree.sha == expected:
    return commit
for commit in default_branch.commits:
  if commit.tree.sha == expected:
    return commit
for branch in all_other_branches:
  for commit in branch.commits:
    if commit.tree.sha == expected:
      return commit
return None
```

Thank you for your time, Chris.

**Comment by dehann** [comment]
Hi All (again),

> [With automation, to register and tag a package the user ...] chooses a tag / branch using Registrator's Interface, but this doesn't affect TagBot's actions

e.g.: https://github.com/JuliaRobotics/Caesar.jl/issues/578#issue-666007091

> When you choose a branch with Registrator, it just translates that into a commit (whatever is on the tip of that branch). So TagBot then tags that commit ... [but does not guarantee the tag to land on the user specified branch, rather more likely to select the "default branch" with equivalent code].

Similar to a previous case: https://github.com/JuliaRegistries/TagBot/issues/159#issuecomment-643852293 

This problem came up again for me, but this time in a different way:  We use specialized Travis tests based which branch is being used (too long to explain here why, but it's important).  So regardless of (*git-tree-sha*) equivalence in code, it's gets tricky when Tagbot randomly uses a different branch for tagging than specified during the registration process.  Unfortunately, so while the improvements to Tagbot are ongoing, I will likely have to (unwillingly) revert to manual tagging after `@JuliaRegistrator` automation.

Perhaps this is something the Julia Computing folks could help out with to speed things along on Tagbot -- to get Tagbot working in a slightly wider category of use-cases.  It should not be a big upgrade, especially considering previous progress (#159 & #161).  I do appreciate time and resources are limited (and everybody is just helping out), but this does seem like an important requirement to me.  It would be cool to have the both the release/tagging pipeline automated for the specific release branch case, as the title of this issue suggests, and not limit developers to the use-git-in-default-branch-only configuration.  

Perhaps I could be so bold and ask @StefanKarpinski  (Hi!) if there is perhaps scope to support such a feature request / enhancement on Tagbot please?  I ask in the spirit of using Julia in a more production type setting, and believe this issue is important enough "to put my hand up" and ask...

**Comment by StefanKarpinski** [comment]
I haven't done any work on TagBot and I don't think that anyone else at JC has either — this tool is pretty much @christopher-dG's baby. I also don't really understand what this issue is about.

**Comment by christopher-dG** [comment]
At risk of giving myself a deadline, I'll get to it this week.
