### ISSUE TITLE
Squashed PRs do not show up in release notes

### ISSUE THREAD

**Issue by omus** [JuliaRegistries/TagBot#19]
Only PRs which have been merged will show up in the release notes. It would be good to also include squashed or rebased PRs which should be possible to detect by looking for `r"\(#\d+\)$"` in the commit message.

**Comment by christopher-dG** [comment]
It's a bit more complicated, otherwise we'd end up with some commits that just mention PRs or issues classified as merged PRs. It'll just require some extra lookups of the captured numbers.

**Comment by christopher-dG** [comment]
Looks like there are a number of changelog generators out there, it might be better to use one of those instead of letting the complexity creep in here. Probably best to go with the first as it won't require any hacking on Lambda's runtime environment. 

- https://github.com/git-chglog/git-chglog
- https://github.com/github-changelog-generator/github-changelog-generator
- https://github.com/lob/generate-changelog
- https://github.com/nokia/git-changelog-generator

**Comment by christopher-dG** [comment]
Turns out the only good one of these is https://github.com/github-changelog-generator/github-changelog-generator, since it actually uses the GitHub API to see what issues/PRs have been closed/merged. Thankfully Lambda supports Ruby too (https://github.com/JuliaRegistries/TagBot/commit/7084ba7243d1dbcaff4c8dab3339b17e9bd9902e).
