### ISSUE TITLE
TagBot not updating repo

### ISSUE THREAD

**Issue by ctkelley** [JuliaRegistries/TagBot#229]
There have been two recent discussions on discourse about TagBot's failing to update package repos. I am not sure discourse was the right place and am raising this issue in the event nobody knows about this.

https://discourse.julialang.org/t/slow-tagbot-no-repo-update-after-16-hours/80870

https://discourse.julialang.org/t/tagbot-github-action-runs-successfully-but-a-new-release-does-not-show-up-on-github-releases/80770/10

**Comment by DilumAluthge** [comment]
There are two separate issues here.

---

> https://discourse.julialang.org/t/slow-tagbot-no-repo-update-after-16-hours/80870

As discussed in that thread, the GitHub API was returning 5xx error codes, which usually indicates an issue on the server side, not on the client (TagBot) side.

> https://discourse.julialang.org/t/tagbot-github-action-runs-successfully-but-a-new-release-does-not-show-up-on-github-releases/80770/10

This logs shows:

```
github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/reference/git#create-a-tag-object"}
```

This is because GitHub has changed the default permissions of the `GITHUB_TOKEN` for new repositories, as reported in https://github.com/JuliaRegistries/CompatHelper.jl/issues/416. This issue will be fixed by #236.
