### ISSUE TITLE
Seems like tagbot is triggered but can't see new Oceananigans v0.77.1

### ISSUE THREAD

**Issue by navidcy** [JuliaRegistries/TagBot#243]
The first automated trigger was
https://github.com/CliMA/Oceananigans.jl/actions/runs/2758338807/attempts/1

Then I tried a couple of times to trigger manually
https://github.com/CliMA/Oceananigans.jl/actions/runs/2758338807/attempts/2
https://github.com/CliMA/Oceananigans.jl/actions/runs/2758338807/attempts/3

but both times `No new versions to release` is returned:
https://github.com/CliMA/Oceananigans.jl/runs/7888083602?check_suite_focus=true#step:3:40

**Comment by DilumAluthge** [comment]
It's been more than 3 days (https://github.com/JuliaRegistries/General/pull/65252) since 0.77.1 was registered.

Therefore, if you trigger a manual run, you'll need to increase the lookback period so that TagBot is able to find the merged PR. See e.g. https://github.com/JuliaRegistries/TagBot/blob/master/README.md#lookback-period

**Comment by navidcy** [comment]
Thanks!
