### ISSUE TITLE
No TagBot trigger issue opened for new package

### ISSUE THREAD

**Issue by junyuan-chen** [JuliaRegistries/TagBot#253]
Does the `TagBot.yml` shown on `README.md` give sufficient permission? I used this setting but there is no TagBot trigger issue opened when a new package is registered on `General` registry. Manually starting the workflow gets things work, but that issue was not created as expected.

**Comment by singularitti** [comment]
Is it possible that the bot comments `@JuliaRegistrator register` in a commit message? Like below:

<img width="870" alt="image" src="https://user-images.githubusercontent.com/25192197/212781331-48f6467d-7e3a-436c-88a9-2bc8a949a84d.png">

**Comment by junyuan-chen** [comment]
@singularitti Thanks for replying! This is indeed how I registered the package. In case more context is needed, here is the link: https://github.com/junyuan-chen/ConfidenceBands.jl/commit/24c1541db1f505633dae23c0bc3e92ef6fd89f70

I made several packages and this was the first time I encountered such a problem. The only difference I made was that I used the updated `TagBot.yml` on `README.md`. That's why I suspected this could be the cause.

**Comment by singularitti** [comment]
I do not have this problem but the Tag Bot does seem to have other bugs recently. I hope someone could have a look at it.

**Comment by ViralBShah** [comment]
It seems to be working fine for a while now.

**Comment by anchal-physics** [comment]
I'm facing same issue on multiple repositories:
## Repositories
https://github.com/ProjectTorreyPines/IMASggd.jl

https://github.com/ProjectTorreyPines/SOLPS2imas.jl

## Action setup
Both repositories are using reusable workflow definition stored in https://github.com/ProjectTorreyPines/GitHubActionsWorkflows/blob/master/.github/workflows/tag_bot.yml

Note that this reusable workflow uses the same file as described on `README.md` but I renamed the file to tag_bot.yml to match filename case with other files.

## Description of issue
First I tried this in [IMASggd](https://github.com/ProjectTorreyPines/IMASggd.jl) while registering 2.0.1 . The registration went through fine but the TagBot did not get triggered. No issue was created and thus no comment was made by JulaTagBot. I thought that maybe the issue is that JuliaTagBot is looking for a TagBot.yml file in the workflow directory and since I changed the name of the file, it could not verify if TagBot action is active or not (although it was visible as TagBot actions in list of available actions in GitHub webpage). Then, I first tried to run the workflow manually to make sure everything else is fine. And it is. The workflow [ran fine](https://github.com/ProjectTorreyPines/IMASggd.jl/actions/runs/12996308506) and generated the [new tag](https://github.com/ProjectTorreyPines/IMASggd.jl/releases/tag/v2.0.1).

So to test the 'file name not matching' hypothesis, in another repo, [SOLPS2imas](https://github.com/ProjectTorreyPines/SOLPS2imas.jl), where I was also releasing a new version, I added TagBot with the filename as TagBot.yml but I face the same issue as before. No new issue was opened by JuliaTagBot and no comment was made because of which the action never triggered.

Not sure what is wrong. Should I open a new issue called "TagBot trigger issue" and close it and hope JuliaTagBot will be able to write comments on it in future?

**Comment by ViralBShah** [comment]
I suggest at least opening a new issue (since it has been working reliably and might have broken for some other reason this time).
