### ISSUE TITLE
Tagbot without Cron job

### ISSUE THREAD

**Issue by aminya** [JuliaRegistries/TagBot#62]
Is there a way to trigger TagBot instead of using a schedule?

**Comment by DilumAluthge** [comment]
Not currently, due to limitations on GitHub Actions.

**Comment by christopher-dG** [comment]
[Here's a forum post to track.](https://github.community/t5/GitHub-Actions/Cross-repository-events/m-p/30951#M620)

**Comment by tkf** [comment]
Maybe this is too naive and/or too cumbersome, but can't JuliaRegistrator (or some other bots) open an issue in the package repository after the registration? If TagBot is hooked to the issue event, it can work without cron job?

**Comment by christopher-dG** [comment]
This is really smart! That would indeed work. 

Something slightly less intrusive would be to create one issue and then comment on that same issue every time. That way, the trigger can be `issue_comment` and the issue tracker doesn't get too clogged.

Naturally, we'd need to restrict who's allowed to trigger tags with comments to whatever bot account is doing the commenting.
But it would still be easy to support custom registries because that username can be configurable.

**Comment by fredrikekre** [comment]
Is JuliaRegistrator allowed to do that? It does not have write access.

**Comment by christopher-dG** [comment]
No, it would need to have a "real" token.

**Comment by christopher-dG** [comment]
I'm gonna start working on this sometime soon, it'll be for v2 so opt-in.

**Comment by christopher-dG** [comment]
closing this in favour of #125, there's more discussion there.
