### ISSUE TITLE
Feature request: tag message & release notes

### ISSUE THREAD

**Issue by maleadt** [JuliaRegistries/TagBot#8]
With GitHub releases, I often added a description of the release using the web interface.
For example, [this release](https://github.com/JuliaGPU/CUDAnative.jl/releases/tag/v2.0.1).

With JuliaRegistrator+TagBot, it looks like the release notes are copied from the tag message (specified with `-m` if created manually), as can be seen [here](https://github.com/JuliaGPU/CUDAnative.jl/releases/tag/v2.1.0) (manually created tag with a re-triggered release via TagBot). But there's no way to specify that message, and manually creating the tag + retriggering TagBot circumvents most of the bot's functionality.

It would be convenient if TagBot would look at the comment/issue that invokes JuliaRegistrator to pick up on a message, and use that for the tag message and/or the release notes (having a tag message makes it useful for `git` users too, and not only GitHub users).

Some possibly syntaxes:

````
@JuliaRegistrator register()

<message>
````

````
@JuliaRegistrator register()

Release notes:

```
<message>
```
````

````
@JuliaRegistrator register()

@TagBot message

```
<message>
```
````

**Comment by christopher-dG** [comment]
Coincidentally, I actually started working on an automated changelog from commit messages today.
I'm not really sure if I want to take it in the direction you mention with Registrator comments, because I'd rather keep usage simple and also keep Registrator and TagBot at least somewhat decoupled.

What I was planning was to make the GitHub release message just the commit titles, aka:

```
- Latest commit
- Less recent commit
- Older commit
```

And now that you mention it, I could use that as a tag message too. The only thing is that GitHub release notes can be edited, Git tag messages cannot. So whatever we do for the tag message is permanent.
What if we use the commit log for the tag message and release notes, but add a line to the tag message "See github.com/foo/bar/releases/x for full release notes"? Then you could edit your GitHub release notes however you want, and have non-GitHub users still be able to easily locate them.

**Comment by maleadt** [comment]
> I'm not really sure if I want to take it in the direction you mention with Registrator comments, because I'd rather keep usage simple and also keep Registrator and TagBot at least somewhat decoupled.

Maybe that could be the fallback behavior, when no message is specified.

> What if we use the commit log for the tag message and release notes, but add a line to the tag message "See github.com/foo/bar/releases/x for full release notes"?

To me, that feels like redundant information because if you're inspecting the tag message, you have direct access to the git log anyway (either by doing a `git log v2.0.1`, or by clicking through to the list of commits). Also, embedding a link to GitHub, which might also go stale, doesn't feel right.

It might also be useful for Pkg to render this information at some point in the future (upon request, or when upgrading). It would not be ideal to default to a possibly lengthy list of commits then.

> Then you could edit your GitHub release notes however you want, and have non-GitHub users still be able to easily locate them.

I'm actually mostly interested in cutting down on maintainer UI interactions for tagging a release and providing release notes, wherever those are saved. So I guess this issue mostly deals with the UI side of things, and to avoid having to go back and edit the release notes on GitHub.com.

**Comment by christopher-dG** [comment]
Thanks for the feedback! I think I agree with you now, and this would be a good thing. I'll open an issue on Registrator to get the ball rolling.

**Comment by christopher-dG** [comment]
Patch notes are now deployed on TagBot's side, and the PR implementing it on the Registrator side is merged but AFAIK not yet deployed. The last thing I need to do is add docs to Registrator.

**Comment by christopher-dG** [comment]
Also to note is that the Git tag will not have the patch notes as its message currently, this is due to either a GitHub API bug or incorrect API usage by me. I've sent in a support request so if I find a solution I'll make the appropriate changes, but for now the patch notes only appear in the GitHub release.

**Comment by christopher-dG** [comment]
Entirely unsurprisingly, the tag message problem was on my end, and has now been fixed :slightly_smiling_face:.

**Comment by fredrikekre** [comment]
> Also to note is that the Git tag will not have the patch notes as its message currently

I am not sure this is so bad. For the notes that end up on the GitHub release you can use markdown etc, which you might not want included in git.

**Comment by christopher-dG** [comment]
You can edit the GitHub release to add styling if you want, but you cannot edit the tag. So if I had to choose between the tag not getting the notes and having to tweak the GitHub release every now and then, I'd take the latter.

**Comment by christopher-dG** [comment]
I think I can close this now, since all the necessary PRs are in :slightly_smiling_face:
