### ISSUE TITLE
No matching commit was found

### ISSUE THREAD

**Issue by omus** [JuliaRegistries/TagBot#80]
The following warning was noticed:
```
No matching commit was found for version v0.13.0 (c7b8fd2450a6e887da2fe5ed02178744a907aae7)
```
https://github.com/invenia/Memento.jl/actions/runs/48869406

Possibly this should be an error as this is the primary function of TagBot.

**Comment by christopher-dG** [comment]
Very weird... the commit gets picked up when I run it locally. Will investigate further!

**Comment by christopher-dG** [comment]
Oh I see what's happening. The release was just made today, but the commit is 6 days old, which is beyond the default 3 day limit.
Assuming that releases will always be made right after commits is definitely not a valid assumption, so that needs fixing.

If you want a quick fix for Memento, you can set `lookback: 7` in the workflow file.

**Comment by christopher-dG** [comment]
Should be fixed by 8115dfc911c9b2872488515be6b4343f5dc820b2 and you won't need to update your workflow at all.

**Comment by christopher-dG** [comment]
yay! https://github.com/invenia/Memento.jl/releases/tag/v0.13.0

**Comment by omus** [comment]
Thanks @christopher-dG! You rock!
